In [2]:
#import essentials libraries
import pandas as pd
import numpy as np
!pip install lazypredict
import lazypredict

In [3]:
data=pd.read_csv("IRIS.csv")
data.head()


sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
x=data.drop(['species'],axis=1)
y=data['species']

In [5]:
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split

In [6]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [7]:
clf=LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,pred=clf.fit(xtrain,xtest,ytrain,ytest)

100%|██████████| 29/29 [00:01<00:00, 27.37it/s]


In [8]:
print(models)

                               Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
LGBMClassifier                     1.00               1.00    None      1.00   
BaggingClassifier                  1.00               1.00    None      1.00   
SVC                                1.00               1.00    None      1.00   
SGDClassifier                      1.00               1.00    None      1.00   
DecisionTreeClassifier             1.00               1.00    None      1.00   
RandomForestClassifier             1.00               1.00    None      1.00   
QuadraticDiscriminantAnalysis      1.00               1.00    None      1.00   
ExtraTreesClassifier               1.00               1.00    None      1.00   
KNeighborsClassifier               1.00               1.00    None      1.00   
NuSVC                              1.00               1.00    None      1.00   
LogisticRegression                 1.00 

In [9]:
from sklearn.ensemble import RandomForestClassifier

classifier=RandomForestClassifier()
classifier.fit(xtrain,ytrain)
ypred=classifier.predict(xtest)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

print(confusion_matrix(ytest,ypred))

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [11]:
print(classification_report(ytest,ypred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.93      1.00      0.96        13
 Iris-virginica       1.00      0.83      0.91         6

       accuracy                           0.97        30
      macro avg       0.98      0.94      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [12]:
print(accuracy_score(ytest,ypred))

0.9666666666666667


In [13]:
data.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145          6.70         3.00          5.20         2.30  Iris-virginica
146          6.30         2.50          5.00         1.90  Iris-virginica
147          6.50         3.00          5.20         2.00  Iris-virginica
148          6.20         3.40          5.40         2.30  Iris-virginica
149          5.90         3.00          5.10         1.80  Iris-virginica

In [15]:
print(classifier.predict((np.array([[6.30,2.50,5.00,1.90]]))))

['Iris-virginica']
